### ISSUE TITLE
初期設定アイテムが一部英語のままになる事象

### ISSUE THREAD

**Issue by doumoku** [AdmiralNyar/CoC7ja#16]
環境：fvtt(v11.308)、CoC7th(0.10.11)

事象：「初期設定」アイテムの技能の一部が英語のままで表示されてしまう。
![image](https://github.com/AdmiralNyar/CoC7ja/assets/126391338/d865152c-f880-4922-9f98-5f3626677b52)

解決策1：各技能のCoC IDのPriority（優先度）を1に設定することで解消、新探索者作成の際も日本語で表示されるように。
![image](https://github.com/AdmiralNyar/CoC7ja/assets/126391338/c31e8198-e1d7-4dc5-a1b3-10b9bed90bbf)

**Comment by AdmiralNyar** [comment]
報告ありがとうございます。
修正しました。
